### PR TITLE
beta-index page

### PR DESCRIPTION
**Pull request by alaizaz**

### CODE REVIEW

**Comment by alaizaz** [comment]
Updated the background

**Comment by alaizaz** [comment]
Please merge the request.

**Comment by alaizaz** [comment]
> Should it not be "Why use DevOps ?" instead, or "a DevOps" (as opposed to "an DevOps")

Done

**Comment by alaizaz** [comment]
> There is a typo in the button name (extra "r"), it reads "Inforgraphics" instead of "Infographics"

DONE

**Review by kinaly — APPROVED** [review]
I haven't done a thorough check of potential typos, but I believe we run out of time so I'll approve for now

**Pull request merged**
